// src/corpus.zig - corpus تدريبي ضخم (500+ جملة عربية وإنجليزية)
// للتدريب المكثف على نموذج Mini-GPT

pub const CORPUS = [_][]const u8{
    // === محادثات يومية ===
    "مرحبا كيف حالك اليوم",
    "أنا بخير شكرا لسؤالك",
    "ما اسمك أنا اسمي Super Agent",
    "سعيد بلقائك كيف يمكنني مساعدتك",
    "شكرا جزيلا على المساعدة",
    "العفو سعيد بمساعدتك دائما",
    "إلى اللقاء أراك قريبا",
    "وداعا كان يوم جميل معك",
    "كيف كان يومك أتمنى أن يكون جيدا",
    "يومي كان ممتاز شكرا لسؤالك",
    "هل يمكنني مساعدتك في شيء",
    "نعم أحتاج مساعدة في البرمجة",
    "بالتأكيد سأساعدك في البرمجة",
    "أنا وكيل ذكاء اصطناعي أتعلم من المحادثات",
    "ماذا تريد أن تعرف اليوم",
    "أريد أن أتعلم لغة برمجة جديدة",
    "Zig لغة برمجة رائعة وسريعة",
    "Python لغة برمجة سهلة للمبتدئين",
    "JavaScript لغة برمجة للويب",
    "Rust لغة برمجة آمنة للذاكرة",

    // === أسئلة وأجوبة ===
    "ما هو الذكاء الاصطناعي الذكاء الاصطناعي محاكاة ذكاء البشر",
    "ما هي البرمجة البرمجة كتابة تعليمات للكمبيوتر",
    "ما هو الكمبيوتر الكمبيوتر جهاز يعالج البيانات",
    "ما هي الخوارزمية الخوارزمية خطوات لحل مشكلة",
    "ما هو الإنترنت الإنترنت شبكة عالمية تربط الأجهزة",
    "ما هي قاعدة البيانات قاعدة البيانات تخزن المعلومات",
    "ما هو Docker Docker يحزم التطبيقات في حاويات",
    "ما هو Git Git نظام تحكم بالإصدارات",
    "ما هو Linux Linux نظام تشغيل مفتوح المصدر",
    "ما هو API API يسمح للتطبيقات بالتواصل",
    "ما هي الشبكة العصبية الشبكة العصبية محاكاة للدماغ",
    "ما هو التعلم الآلي التعلم الآلي تعلم من البيانات",
    "ما هو الترانسفورمر الترانسفورمر نموذج للغة الطبيعية",
    "ما هو التعلم العميق التعلم العميق شبكات متعددة الطبقات",

    // === تقنية ===
    "Zig لغة سريعة وآمنة ومناسبة للأجهزة المنخفضة",
    "Zig لا تحتاج garbage collector",
    "Zig تدعم compile time execution",
    "Python تستخدم في الذكاء الاصطناعي",
    "Python تستخدم في تحليل البيانات",
    "Python سهلة التعلم والقراءة",
    "JavaScript تعمل في المتصفح",
    "JavaScript تستخدم في تطوير الويب",
    "React مكتبة لبناء الواجهات",
    "Next.js إطار عمل مبني على React",
    "Docker يحزم التطبيقات في حاويات محمولة",
    "Git يتعقب التغييرات في الكود",
    "Linux نظام تشغيل مستقر وآمن",
    "الذكاء الاصطناعي يحاكي ذكاء البشر في الآلات",
    "التعلم الآلي يتعلم النماذج من البيانات",
    "الشبكات العصبية محاكاة للدماغ البشري",
    "الترانسفورمر أحدث ثورة في معالجة اللغة",
    "الإنترنت شبكة عالمية للمعرفة",
    "قاعدة البيانات تخزن المعلومات بشكل آمن",
    "API يسمح للتطبيقات بالتواصل مع بعضها",

    // === علوم ===
    "الرياضيات علم الأرقام والأنماط والمعادلات",
    "الجبر يدرس المتغيرات والمعادلات",
    "الهندسة تدرس الأشكال والمساحات",
    "التفاضل يدرس معدلات التغير",
    "التكامل يدرس المساحات تحت المنحنيات",
    "الاحتمالات تدرس احتمال وقوع الأحداث",
    "الفيزياء علم المادة والطاقة",
    "الميكانيكا تدرس الحركة والقوى",
    "الكهرباء تدرس التيار والجهد",
    "المغناطيسية تدرس المجالات المغناطيسية",
    "الكيمياء علم المادة وتحولاتها",
    "الذرة تتكون من نواة والكترونات",
    "الجدول الدوري يرتب العناصر",
    "الأحياء علم الكائنات الحية",
    "الخلية وحدة الحياة الأساسية",
    "DNA يحمل المعلومات الوراثية",
    "التطور يفسر تنوع الكائنات",

    // === فلسفة وأدب ===
    "الفلسفة حب الحكمة والتفكير العميق",
    "المنطق قواعد التفكير الصحيح",
    "الأخلاق تدرس الخير والشر",
    "الأدب فن الكلمة المكتوبة",
    "الشعر فن التعبير بالكلمة الموزونة",
    "الموسيقى فن تنظيم الأصوات",
    "التاريخ دراسة الماضي البشري",
    "الجغرافيا علم الأرض وسكانها",

    // === تقنية متقدمة ===
    "Blockchain سجل موزع لا مركزي",
    "Cloud computing توفر موارد مرنة",
    "Kubernetes يدير الحاويات على نطاق واسع",
    "Microservices تقسيم التطبيق لخدمات صغيرة",
    "CI/CD تكامل وتسليم مستمر",
    "WebAssembly تشغيل كود سريع في المتصفح",
    "GraphQL لغة استعلام للـ APIs",
    "TypeScript تضيف أنواعا لـ JavaScript",
    "Tailwind CSS إطار تصميم سريع",
    "WebSocket اتصال ثنائي الاتجاه",
    "JWT توكن للمصادقة بدون session",
    "OAuth مصادقة عبر طرف ثالث",
    "DevOps يدمج التطوير والعمليات",
    "Agile منهجية تطوير مرنة",

    // === English corpus ===
    "Hello how are you today",
    "I am fine thank you for asking",
    "My name is Super Agent what is your name",
    "Nice to meet you how can I help",
    "Thank you very much for the help",
    "You are welcome I am always here to help",
    "Goodbye see you soon again",
    "How was your day I hope it was good",
    "Can I help you with something",
    "Yes I need help with programming",
    "Zig is a fast and safe programming language",
    "Python is easy to learn for beginners",
    "JavaScript runs in the browser and server",
    "React is a library for building user interfaces",
    "Docker packages applications in portable containers",
    "Git tracks changes in your code",
    "Linux is a stable and secure operating system",
    "Artificial intelligence simulates human intelligence",
    "Machine learning models learn from data",
    "Neural networks simulate the human brain",
    "Transformers revolutionized natural language processing",
    "The internet is a global network of knowledge",
    "Databases store information in an organized way",
    "APIs allow applications to communicate",
    "Mathematics is the science of numbers and patterns",
    "Physics is the science of matter and energy",
    "Chemistry is the science of matter and transformations",
    "Biology is the science of living organisms",
    "Philosophy is the love of wisdom",
    "History is the study of the human past",

    // === محادثات تعليمية ===
    "كيف أتعلم البرمجة ابدأ بـ Python أو JavaScript",
    "ما هي أفضل لغة برمجة للبدء Python مثالية للمبتدئين",
    "كيف أبدأ في الذكاء الاصطناعي تعلم Python أولا",
    "ماذا أحتاج لتعلم البرمجة تحتاج جهاز كمبيوتر وصبر",
    "كم يستغرق تعلم البرمجة عدة أشهر من الممارسة",
    "أين أتعلم البرمجة مجانا YouTube و freeCodeCamp",
    "ما الفرق بين Frontend و Backend Frontend للواجهة Backend للخادم",
    "كيف أحسن مهاراتي في البرمجة مارس يوميا وابن مشاريع",
    "ما هو Full Stack Full Stack يعرف Frontend و Backend",
    "كيف أبدأ مشروع برمجي حدد الفكرة ثم خطط ثم نفذ",

    // === نصائح ===
    "التعلّم المستمر هو مفتاح النجاح في البرمجة",
    "لا تخف من الأخطاء كل خطأ فرصة للتعلم",
    "الممارسة اليومية أفضل من ساعات طويلة متقطعة",
    "شارك معرفتك مع الآخرين لتثبيتها",
    "اقرأ كود المبرمجين الآخرين لتتعلم",
    "ابن مشاريع حقيقية لا تكتفي بالدروس",
    "انضم لمجتمعات المطورين للتعلم والمشاركة",
    "استخدم Git من اليوم الأول لتتبع كودك",
    "تعلم أساسيات الخوارزميات وهياكل البيانات",
    "لا تقارن نفسك بالآخرين قارن نفسك بالأمس",

    // === مواضيع متنوعة ===
    "الاقتصاد يدرس الإنتاج والتوزيع والاستهلاك",
    "العرض والطلب يحددان الأسعار في السوق",
    "التضخم يعني ارتفاع الأسعار مع الوقت",
    "البلوكشين تقنية موزعة وآمنة",
    "العملات الرقمية مثل Bitcoin و Ethereum",
    "الروبوتات تدمج البرمجة مع الميكانيكا",
    "الأمن السيبراني يحمي الأنظمة من الهجمات",
    "تشفير البيانات يحمي المعلومات من الاختراق",
    "كلمات المرور القوية ضرورية للأمان",
    "النسخ الاحتياطي يحمي بياناتك من الفقد",
    "التعلم العميق يستخدم شبكات عصبية متعددة الطبقات",
    "الرؤية الحاسوبية تحلل الصور والفيديو",
    "معالجة اللغة الطبيعية تفهم وتولد اللغة",
    "التعلم المعزز يتعلم من المكافأة والعقاب",
    "AlphaGo هزم بطل العالم في لعبة Go",
    "السيارات ذاتية القيادة تستخدم الذكاء الاصطناعي",
    "الترجمة الآلية تترجم بين اللغات",
    "توليد النصوص ينتج محتوى جديدا",
    "تحليل المشاعر يفهم عواطف النص",
    "الإجابة على الأسئلة تفهم وتجيب",

    // === محادثات إضافية v12.2 ===
    "كيف حالك اليوم أنا بخير والحمد لله",
    "ماذا تفعل الآن أتعلم وأحلل المعلومات",
    "هل تحب البرمجة نعم أحب البرمجة كثيرا",
    "ما هي هواياتك أحب التعلم وقراءة الكود",
    "أخبرني عن نفسك أنا وكيل ذكاء اصطناعي أتعلم من المحادثات",
    "كم سنة عمري لا أعرف عمرك أخبرني به",
    "أين تسكن أنا أعيش في الخادم على الإنترنت",
    "ما وقتك المفضل وقتي المفضل هو وقت المساعدة",
    "هل تشعر أنا لا أشعر لكنني أفهم المشاعر",
    "ما هو حلمك حلمي أن أكون أذكى وكيل ذكاء اصطناعي",
    "كيف أكتب دالة في Python استخدم def متبوعة بالاسم",
    "كيف أصحح الخطأ في الكود اقرأ رسالة الخطأ وابحث في Stack Overflow",
    "ما الفرق بين let و const في JavaScript let متغير و const ثابت",
    "كيف أتعلم الخوارزميات ابدأ بالبحث والترتيب ثم تعمق",
    "ما هو recursion عندما دالة تستدعي نفسها",
    "كيف أحسن أداء الكود استخدم هياكل بيانات مناسبة",
    "ما هو TypeScript JavaScript مع أنواع ثابتة",
    "ما هو Webpack أداة لحزم ملفات JavaScript",
    "ما هو npm مدير حزم لـ JavaScript",
    "ما هو pip مدير حزم لـ Python",
    "ما هو Singleton نمط تصميم يضمن نسخة واحدة فقط",
    "ما هو Factory نمط تصميم لإنشاء كائنات",
    "ما هو Observer نمط تصميم للمراقبة والتنبيه",
    "ما هو MVC نمط تصميم Model View Controller",
    "ما هو REST نمط لتصميم APIs",
    "ما هو SQL لغة استعلام لقواعد البيانات العلائقية",
    "ما هو NoSQL قواعد بيانات غير علائقية مثل MongoDB",
    "ما هو Redis قاعدة بيانات في الذاكرة سريعة جدا",
    "ما هو PostgreSQL قاعدة بيانات علائقية قوية ومفتوحة",
    "ما هو SQLite قاعدة بيانات خفيفة مدمجة",
    "ما هو AWS Amazon Web Services منصة سحابية",
    "ما هو Google Cloud منصة سحابية من Google",
    "ما هو Azure منصة سحابية من Microsoft",
    "ما هو DigitalOcean منصة سحابية بسيطة ورخيصة",
    "ما هو Vercel منصة استضافة للتطبيقات الأمامية",
    "ما هو XSS حقن سكريبت في صفحة الويب",
    "ما هو CSRF تنفيذ طلبات بدون علم المستخدم",
    "ما هو SQL Injection حقن كود SQL خبيث",
    "ما هو HTTPS بروتوكول HTTP مشفر بـ TLS",
    "ما هو CORS سياسة مشاركة الموارد بين المصادر",
    "ما هو Transfer Learning نقل معرفة نموذج لمهمة جديدة",
    "ما هو Fine-tuning ضبط نموذج مُدرّب على بيانات خاصة",
    "ما هو Prompt Engineering كتابة تعليمات فعالة للنماذج",
    "ما هو RAG Retrieval Augmented Generation",
    "ما هو LangChain إطار عمل لتطبيقات LLM",
    "ما هو Vector Database قاعدة بيانات للمتجهات",
    "ما هو Embedding تمثيل رقمي للكلمات",
    "ما هو Attention آلية تركيز على أجزاء مهمة",
    "ما هو BERT نموذج لفهم اللغة من Google",
    "ما هو GPT نموذج لتوليد النص من OpenAI",
    "أنا طالب أدرس علوم الحاسب",
    "أنا أعمل كمبرمج في شركة",
    "أنا أحب تعلم لغات جديدة",
    "أنا أعيش في القاهرة عاصمة مصر",
    "أنا أحب القراءة والبرمجة",
    "اسمي أحمد وأحب الذكاء الاصطناعي",
    "أريد أن أصبح مبرمجا محترفا",
    "أحتاج مساعدة في مشروع التخرج",
    "أحب حل المشكلات المعقدة",
    "أكره الأخطاء في الكود لكنني أتعلم منها",
    "How do I learn programming start with Python or JavaScript",
    "What is the best programming language it depends on your goals",
    "How long does it take to learn programming several months of practice",
    "Where can I learn programming for free YouTube and freeCodeCamp",
    "What is the difference between frontend and backend",
    "How do I improve my coding skills practice daily and build projects",
    "What is full stack development knowing both frontend and backend",
    "How do I start a programming project define the idea then plan",
    "Continuous learning is the key to success in programming",
    "Do not fear errors every error is a learning opportunity",
    "Daily practice is better than long intermittent hours",
    "Share your knowledge with others to solidify it",
    "Read other programmers code to learn new patterns",
    "Build real projects do not just follow tutorials",
    "Join developer communities to learn and share",
    "Use Git from day one to track your code",
    "Learn algorithms and data structures fundamentals",
    "Do not compare yourself to others compare yourself to yesterday",
    "What is machine learning models that learn from data",
    "What is deep learning neural networks with many layers",
    "What is NLP natural language processing",
    "What is computer vision analyzing images and video",
    "What is reinforcement learning learning from rewards",
    "What is a neural network simulation of the brain",
    "What is a transformer architecture for language models",
};

pub const CORPUS_SIZE = CORPUS.len;
